brew 'imagemagick'
brew 'node'
brew 'parallel'
brew 'phantomjs'
brew 'postgresql'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tmux'
brew 'vim'
brew 'zsh'

tap 'thoughtbot/formulae'
brew 'pick'
