# Common Fish Aliases
alias ls 'ls -G'
alias ll 'ls -l'
alias la 'ls -a'
alias grep 'grep --color=auto'
alias vi 'vim'
alias cls 'clear'
alias .. 'cd ..'
alias ... 'cd ../..'
alias .... 'cd ../../..'
alias ..... 'cd ../../../..'

# Common Git Aliases
alias g 'git status'
alias ga 'git add'
alias gap 'git add -p'
alias grim 'git rebase -i main'
alias gb 'git branch'
alias gc 'git commit --verbose'
alias gco 'git checkout'
alias gcm 'git checkout main'
alias gl 'git log'
alias gd 'git diff'
alias gpull 'git pull'
alias gpush 'git push'
alias gclone 'git clone'
alias gmerge 'git merge'
alias grs 'git reset --soft'
alias gstash 'git stash'
alias gcherry 'git cherry-pick'
alias gs 'git show'
alias ggrep 'git grep'
alias gmv 'git mv'
alias grm 'git rm'
alias gcan 'git commit --amend --no-edit'
alias gignore 'git update-index --assume-unchanged'
alias gunignore 'git update-index --no-assume-unchanged'
alias ggraph 'git log --graph --oneline --decorate --all'
alias glog 'git log --oneline --decorate --all'

# Alias for committing work in progress
alias wip 'function __wip; git commit -m "WIP: $argv"; end; __wip'
# Alias for committing work in progress with patch add
alias wap 'function __wap; git add -p && git commit -m "WIP: $argv"; end; __wap'
alias gsw 'git stash && git switch'
alias :q 'exit'
alias cm 'chezmoi'
alias dotfiles 'chezmoi edit'
