# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Hide the username. The username will only show in certain scenarios
[username]
disabled = true

# shows the hostname on new lines
[hostname]
ssh_only = true
disabled = false

[cmd_duration]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[lua]
disabled = true
